### PR TITLE
Closes #44: Add toc plugin

### LINKED ISSUE #44: Support toc in markdown page
Similar to https://vuepress.vuejs.org/guide/markdown.html#table-of-contents

Replace `[[toc]]` with the actual Table of Contents.

### PR DESCRIPTION
**Pull request by MarchWorks**
**Summary**
Closes #44
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI/CSS related code, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by krmax44** [comment]
Hmm... now that `injectMarkdownHeadings` is implemented and it being enabled by default, I'm wondering if this could be simplified into a Vue component, grabbing `page.attributes.markdownHeadings` and rendering out the table of contents.

**Comment by MarchWorks** [comment]
@krmax44 we are discussing that in the issue

**Comment by krmax44** [comment]
> @krmax44 we are discussing that in the issue

Sorry, didn't see that one :eyes:

**Comment by MarchWorks** [comment]
Closing this

**Pull request closed without merging**
