### PR TITLE
fix(saber-plugin-image): fix lazy load for images with `srcset`

### PR DESCRIPTION
**Pull request by kidonng**
**Summary**

Fix lazy loading for images with `srcset`.

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI/CSS related code, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by krmax44** [comment]
The feature seems handy, yet that shouldn't be used as a workaround for a bug :laughing: Could you file an issue so we can resolve the `srcset` lazyloading problem?

**Comment by kidonng** [comment]
> The feature seems handy, yet that shouldn't be used as a workaround for a bug 😆 Could you file an issue so we can resolve the `srcset` lazyloading problem?

Well, I only confirmed that problem on Firefox and I'm not sure whether it's the correct behavior (though it breaks lazy load), and since I don't need mutilple sizes I would go for a option to disable `srcset` 😃 yeah it do looks like a lazy solution.

**Comment by egoist** [comment]
@krmax44  I'm not sure how lazyload actually works in this plugin, but it seems all the images on the page will be loaded, is this expected?

屏幕快照 2019-06-17 下午10 06 57

**Comment by krmax44** [comment]
> @krmax44 I'm not sure how lazyload actually works in this plugin, but it seems all the images on the page will be loaded, is this expected?
> 
> 屏幕快照 2019-06-17 下午10 06 57

The issue is, as @kidonng mentioned, that lazy-loading is bugged with `srcset`. Either the props are passed incorrectly to `vue-lazyload` or it's a flaw with the library itself (related #196).

**Comment by kidonng** [comment]
Source:
```html
<img alt="Simple, beautiful input fields with Vue.js" width="1000" height="242" src="/_saber/images/beautiful-inputs.4ce2726d.svg" data-v-160b41dc>
```

Rendered:
```html
<img alt="Simple, beautiful input fields with Vue.js" width="1000" height="242" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" data-v-160b41dc="" data-src="/_saber/images/beautiful-inputs.4ce2726d.svg" lazy="loading">
```

**Comment by kidonng** [comment]
I happen to find this may be caused by #197.

> But there's another problem: we can't support SSR at the same time (that is, render images as  in HTML, not ) because browsers will load images from the attribute first, making lazy load invalid.

My previous statement seems wrong, we can preserve `src` along with `srcset`... I will consider making another PR to perfect it. (and close #196 as well!)

**Pull request merged**
