### PR TITLE
refactor: rewrite core in typescript

### PR DESCRIPTION
**Pull request by egoist**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [x] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI/CSS related code, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] Briefly describing what this PR does in the title in [Angular Commit Message Conventions](https://git.io/fNGDG), e.g. `fix: rebuild when a page is added`

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by egoist** [comment]
I'll merge it once those `@ts-ignore`, `TODO` and lint errors get fixed.

**Comment by egoist** [comment]
image

Netlify stuck at `Enqueued` stage for an hour already 😅

**Comment by krmax44** [comment]
I'll take a look in the coming days.

**Comment by egoist** [comment]
@krmax44 the core is in TypeScript now we can migrate the rest progressively 😄 

preview

**Pull request merged**
