### PR TITLE
build: move CI to GitHub actions

### LINKED ISSUE #436: Move CI to GitHub actions
GitHub Actions works with Linux, macOS and Windows and it's free for OSS. I think it's a good idea to test Saber on Windows as well 😄

### PR DESCRIPTION
**Pull request by egoist**
**Summary**

Closes #436

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [x] Build-related changes
- [ ] Other, please describe:

If changing the UI/CSS related code, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] Briefly describing what this PR does in the title in [Angular Commit Message Conventions](https://git.io/fNGDG), e.g. `fix: rebuild when a page is added`

### CODE REVIEW

**Comment by egoist** [comment]
Great, except that GitHub actions is 1 minute slower than CirCleCI because it didn't cache `node_modules` 🤔

**Comment by egoist** [comment]
Hmm not sure why Prettier is complaining about carriage returns: https://github.com/saberland/saber/pull/451/checks?check_run_id=222280251#step:5:16

**Comment by MarchWorks** [comment]
@egoist it happens for me locally

**Comment by egoist** [comment]
@the94air sorry for spamming you 😆

**Pull request merged**
