### PR TITLE
Add toc plugin

### LINKED ISSUE #44: Support toc in markdown page
Similar to https://vuepress.vuejs.org/guide/markdown.html#table-of-contents

Replace `[[toc]]` with the actual Table of Contents.

### PR DESCRIPTION
**Pull request by MarchWorks**
Closes #44 Hope that I have done everything right

### CODE REVIEW

**Comment by egoist** [comment]
Can you add a test case? similar to https://github.com/egoist/saber/blob/master/packages/saber/lib/markdown/highlight-plugin.test.js

**Comment by MarchWorks** [comment]
@egoist what should I do to create the snapshot?

**Comment by MarchWorks** [comment]
@egoist Done, should I fix these errors? but there is some that I can't like `no-negated-condition`


`

**Comment by MarchWorks** [comment]
I solved most of the inistial issues but there is two that I can't do anything about so I added
```
"no-negated-condition": "off",
"unicorn/number-literal-case": "off"
```
to `xo` rules

**Comment by egoist** [comment]
We should probably implement #51 first.

**Comment by MarchWorks** [comment]
sorry I was trying to push into a branch

**Comment by MarchWorks** [comment]
@egoist I created `TOC.vue` but I don't know how to get it used by this plugin (by saber generally) so of course I keep getting `[Vue warn]: Unknown custom element: <TOC>` should it get added to `LayoutManager.vue` somehow or what

**Pull request closed without merging**
