### PR TITLE
feat(saber-plugin-image): replace `vue-lazyload` with `lozad`

### LINKED ISSUE #196: chore: Replace vue-lazyload with a custom library
[Issuehunt badges](https://issuehunt.io/r/saberland/saber/issues/196)

## Feature request

Replace `vue-lazyload` with a custom library. Related #197

#### What problem does this feature solve?

`vue-lazyload` isn't properly maintained and is missing some features like events plus it has a couple of weird bugs.

#### What does the proposed API look like?

Simple API with events and stricter configuration - `vue-lazyload`'s one is pretty loose with too many options that can cause conflicts or straight up don't work sometimes.

#### How should this be implemented in your opinion?

Either straight in `SaberImage` or as a seperate library. Thoughts?

#### Are you willing to work on this yourself?

Yes.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $100.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($100.00)
### Submitted pull Requests
- [#356 refactor(saber-plugin-image): replace `vue-lazyload` with `lozad`](https://issuehunt.io/r/saberland/saber/pull/356)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/saberland/saber/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by kidonng**
**Summary**

Motivation: https://github.com/saberland/saber/pull/264#issuecomment-514324599

This PR:

- Refactor: replace `vue-lazyload` with `lozad`, close #196 
- Refactor: use new lazyload method to preserve `src`, supporting browsers without `srcset` support, feed generator, spiders...
- Fix: modify fixed transition style, allowing custom style to apply
- Fix: remove height attribute, allowing responsive image

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [x] Refactor
- [x] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI/CSS related code, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#196: chore: Replace vue-lazyload with a custom library](https://issuehunt.io/repos/134598900/issues/196)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

Published PR with canary version: <details><summary>Canary Versions</summary>
 - `extract-sfc-blocks@0.0.3-canary.356.aaea14a.0`
 - `create-blog@0.2.8-canary.356.aaea14a.0`
 - `create-site@0.3.2-canary.356.aaea14a.0`
 - `saber-highlight-css@0.1.1-canary.356.aaea14a.0`
 - `saber-highlighter-prism@0.3.2-canary.356.aaea14a.0`
 - `saber-log@0.2.1-canary.356.aaea14a.0`
 - `saber-markdown@0.1.1-canary.356.aaea14a.0`
 - `saber-plugin-feed@0.4.1-canary.356.aaea14a.0`
 - `saber-plugin-git-modification-time@0.1.1-canary.356.aaea14a.0`
 - `saber-plugin-google-analytics@0.1.1-canary.356.aaea14a.0`
 - `saber-plugin-image@0.1.1-canary.356.aaea14a.0`
 - `saber-plugin-meta-redirect@0.1.1-canary.356.aaea14a.0`
 - `saber-plugin-netlify-redirect@0.1.1-canary.356.aaea14a.0`
 - `saber-plugin-prismjs@0.2.2-canary.356.aaea14a.0`
 - `saber-plugin-pwa@0.4.1-canary.356.aaea14a.0`
 - `saber-plugin-query-posts@0.4.1-canary.356.aaea14a.0`
 - `saber-plugin-transformer-html@0.1.1-canary.356.aaea14a.0`
 - `saber-plugin-transformer-pug@0.1.1-canary.356.aaea14a.0`
 - `saber-utils@0.2.1-canary.356.aaea14a.0`
 - `saber@0.7.1-canary.356.aaea14a.0`</details>

### CODE REVIEW

**Comment by kidonng** [comment]
@krmax44 Can we move the inline transition style to stylesheet? It will override styles added by other libraries such as [medium-zoom](https://github.com/francoischalifour/medium-zoom).

**Comment by krmax44** [comment]
> @krmax44 Can we move the inline transition style to stylesheet? It will override styles added by other libraries such as [medium-zoom](https://github.com/francoischalifour/medium-zoom).
> 
> If one wants to change the duration, they can use custom styles to override the defaults.

Absolutely.

**Comment by kidonng** [comment]
Done.

Guess nobody is actually passing numbers to `blendIn` or this might be a little breaking 😂

**Comment by egoist** [comment]
There is a lint error.

**Comment by kidonng** [comment]
> There is a lint error.

That variable is [ejected](https://github.com/saberland/saber/blob/e675ce95c203b3d42f9df2685219fbfa5b722a15/packages/saber-plugin-image/lib/index.js#L71).

**Comment by egoist** [comment]
Yes, I mean, can you fix it?

**Comment by kidonng** [comment]
It is there from the beginning and I think that's how other plugins handle config (e.g. [`saber-plugin-google-analytics`](https://github.com/saberland/saber/blob/e675ce95c203b3d42f9df2685219fbfa5b722a15/packages/saber-plugin-google-analytics/saber-browser.js#L7)).
It is given [a default value](https://github.com/saberland/saber/blob/e675ce95c203b3d42f9df2685219fbfa5b722a15/packages/saber-plugin-image/lib/index.js#L71) so we shouldn't worry about that.

**Comment by kidonng** [comment]
😅 Sorry I understand what you mean now
Anyway thanks

**Comment by egoist** [comment]
`vue-lazyload` can be removed now, readme should also get updated.

**Pull request merged**
