### PR TITLE
resolve #80: assets handling in page attributes

### LINKED ISSUE #80: feat: Asset handling via Frontmatter
Basically https://github.com/vuejs/vuepress/issues/79. Common feature in Hexo and the likes, where you can set assets like a post thumbnail in the frontmatter:

```yaml
---
image: ./thumbnail.png
---
```

### PR DESCRIPTION
**Pull request by egoist**
**Summary**

Automatically process `page.attributes.assets` with webpack:

```markdown
---
assets:
  cover: ./cover.png
---
```

```vue
<template>
	<div>
        <!-- page.attributes.assets.cover will be an absolute url -->
		<img :src="page.attributes.assets.cover" alt="cover">
	</div>
</template>

<script>
export default {
  props: ['page']
}
</script>
```

- URL starting with `https?://` is not processed
- URL starting with `/` is not processed

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI/CSS related code, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

You have tested in the following browsers: (Providing a detailed version will be better.)

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature
- [ ] Related documents have been updated
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

TODO:

- [ ] Add docs

### CODE REVIEW

**Comment by krmax44** [comment]
Looks great to me! I'll try to test it as soon as possible.

**Comment by krmax44** [comment]
So it didn't work at first start, a small fix was necessary. While I was at it, I also refactored `page-prop-loader.js` to make it more readable. See

https://github.com/krmax44/saber/blob/0643ffcbc30d60db91b559f8b5d6f19033c0f8c6/packages/saber/vue-renderer/lib/page-prop-loader.js

Only one problem remains: when using `injectAllPosts`, the assets are not loaded with webpack and the unresolved `./cover.png` stays.

**Comment by egoist** [comment]
> Only one problem remains: when using injectAllPosts, the assets are not loaded with webpack and the unresolved ./cover.png stays.

hmm we probably need to find another way to solve this then, current imeplementation can't process the attributes in `page.posts`

**Comment by krmax44** [comment]
So I managed to get it working with `plugin-query-posts`, though with some caveats. While it works, it spits out warnings all over the place and I have no clue what's going on.

https://github.com/krmax44/saber/blob/c03d96babcd85c7453db63762f965e7184dda4ec/packages/saber/vue-renderer/lib/page-prop-loader.js#L33

Second, when I change `'@/pages/' + path.join(...)` to `'@/' + path.join('pages/', ...)`, even though the same string is passed to `require()`, it throws an error for the latter, making it impossible to use assets outside of the `pages/` folder. Not an instant deal-breaker, but it shows something is clearly screwed with my code and I just can't seem to grasp what it is.

**Comment by egoist** [comment]
Here's a solution, let's just convert `page.attributes.assets` when creating the page (adding the `!!let_webpack_handle_me!!` prefix):

```js
{
  cover: './foo.png'
}

//=> becomes:

{
  cover: '!!let_webpack_handle_me!!./foo.png'
}

```

Then create a babel plugin or directly hook into webpack's acorn parser to transform the above (strings starting with `!!let_webpack_handle_me!!`) to:

```js
{
  cover: require('./foo.png')
}
```

**Comment by krmax44** [comment]
I'm not much of a webpack expert, but I'll take a crack at it :)

**Comment by egoist** [comment]
Closing this one.

**Pull request closed without merging**
